version: "3.8"

x-dummy: &nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  ragtestdev:
    build: .
    <<: *nvidia
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - ../:/workspaces/ragtest
      - jovyanhome:/home/jovyan
      # - condaenvs:/opt/conda/envs
    networks:
      - ragtest
  pgvector:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    env_file:
      - ../pgpass.env
    networks:
      - ragtest
  ollama:
    build: ollama
    # ports:
    #   - 11434:11434
    volumes:
      - ollama:/home/ollama/.ollama
    networks:
      - ragtest
    <<: *nvidia

volumes:
  ollama:
  jovyanhome:
    # condaenvs:

networks:
  ragtest:
